all: dbclient dbserver

clean:
	rm -f dbclient dbserver database.txt

dbclient: dbclient.c msg.h
	gcc dbclient.c -o dbclient -Wall -Werror -std=gnu99

dbserver: dbserver.c msg.h
	gcc dbserver.c -o dbserver -Wall -Werror -std=gnu99 -pthread
